AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless VPC Page

Parameters:
  ApplicationName:
    Type: String
    Default: 'ServerlessVPCPage'
  FrontPageApiStageName:
    Type: String
    Default: 'ProdStage'
  VpcCidrBlock:
    Type: String
    Default: '192.168.2.0/24'
  VpcName:
    Type: String
    Default: "SampleVPC"
  AZ:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: "ap-northeast-1a"
  PublicSubnetCidrBlock:
    Type: String
    Default: '192.168.2.0/25'
  PublicSubnetName:
    Type: String
    Default: "SamplePublicSubnet"

Resources:
  FrontPageApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ServerlessVPCPageApi
      EndpointConfiguration: REGIONAL
      StageName: !Ref FrontPageApiStageName

  FrontPageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
      - arm64
      FunctionName: ServerlessVPCPageFrontFunction
      CodeUri: bin/
      Handler: bootstrap
      MemorySize: 256
      Runtime: provided.al2
      Description: 'VPC Front Function'
      Environment:
        Variables:
          REGION: !Ref 'AWS::Region'
          API_PATH: !Join [ '', [ '/', !Ref FrontPageApiStageName, '/api'] ]
      Events:
        FrontPageApi:
          Type: Api
          Properties:
            Path: '/'
            Method: get
            RestApiId: !Ref FrontPageApi

  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
      - arm64
      FunctionName: ServerlessVPCPageMainFunction
      CodeUri: api/bin/
      Handler: bootstrap
      MemorySize: 256
      Runtime: provided.al2
      Description: 'VPC API Function'
      Policies:
      - Statement:
        - Effect: 'Allow'
          Action:
            - 'ec2:Describe*'
          Resource: '*'
      Environment:
        Variables:
          REGION: !Ref 'AWS::Region'
          VPC_ID: !Ref SampleVPC
          SUBNET_ID: !Ref SamplePublicSubnet
      Events:
        FrontPageApi:
          Type: Api
          Properties:
            Path: '/api'
            Method: post
            RestApiId: !Ref FrontPageApi

  SampleVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Ref VpcName

  SamplePublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZ
      CidrBlock: !Ref PublicSubnetCidrBlock
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Ref PublicSubnetName
      VpcId: !Ref SampleVPC

Outputs:
  APIURI:
    Description: "URI"
    Value: !Join [ '', [ 'https://', !Ref FrontPageApi, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref FrontPageApiStageName,'/'] ]
